name: real_estate
channels:
 - defaults
 - conda-forge 
dependencies:
  - python=3.13.9
  - pip
  - pip:
    - streamlit>=1.39.0
    - pandas>=2.1.0
    - numpy>=1.26.0
    - altair>=5.3.0
    - joblib==1.5.2     
    - scikit-learn>=1.5.0
    - scipy>=1.13.0
  
  