name: real_estate
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - altair=5.5.0=py313hca03da5_0
  - aom=3.12.1=ha237518_0
  - arrow-cpp=21.0.0=h9e9184e_1
  - attrs=25.4.0=py313hca03da5_2
  - aws-c-auth=0.9.0=h79febb2_2
  - aws-c-cal=0.9.2=h79febb2_1
  - aws-c-common=0.12.4=h79febb2_0
  - aws-c-compression=0.3.1=h79febb2_2
  - aws-c-event-stream=0.5.6=h79febb2_0
  - aws-c-http=0.10.4=h79febb2_0
  - aws-c-io=0.21.4=h79febb2_0
  - aws-c-mqtt=0.13.3=h387b88a_0
  - aws-c-s3=0.8.7=h79febb2_0
  - aws-c-sdkutils=0.2.4=h79febb2_1
  - aws-checksums=0.2.7=h79febb2_1
  - aws-crt-cpp=0.34.0=hee39554_0
  - aws-sdk-cpp=1.11.638=h35fa3df_0
  - blas=1.0=openblas
  - blinker=1.9.0=py313hca03da5_0
  - bottleneck=1.4.2=py313h03d0aa3_1
  - brotlicffi=1.1.0.0=py313h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.11.4=hca03da5_0
  - cachetools=5.5.1=py313hca03da5_0
  - cairo=1.18.4=h191e429_0
  - certifi=2025.11.12=py313hca03da5_0
  - cffi=2.0.0=py313h73c2a22_1
  - charset-normalizer=3.4.4=py313hca03da5_0
  - click=8.2.1=py313hca03da5_0
  - contourpy=1.3.3=py313h20e30b6_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.3=h982b769_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py313h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - gflags=2.2.2=h313beb8_1
  - gitdb=4.0.12=py313hca03da5_0
  - gitpython=3.1.45=py313hca03da5_0
  - glog=0.5.0=h313beb8_1
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - idna=3.11=py313hca03da5_0
  - jansson=2.14=h80987f9_1
  - jinja2=3.1.6=py313hca03da5_0
  - joblib=1.5.2=py313hca03da5_0
  - jpeg=9f=h2f69dba_0
  - jsonschema=4.25.0=py313hca03da5_1
  - jsonschema-specifications=2025.9.1=py313hca03da5_0
  - kiwisolver=1.4.8=py313h313beb8_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libavif=1.1.1=h96d1633_1
  - libbrotlicommon=1.0.9=h80987f9_9
  - libbrotlidec=1.0.9=h80987f9_9
  - libbrotlienc=1.0.9=h80987f9_9
  - libcurl=8.16.0=h01d3526_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libgrpc=1.71.0=h62f6fdd_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.8=h9681e36_0
  - libmpdec=4.0.0=h80987f9_0
  - libnghttp2=1.67.1=h8189af8_0
  - libopenblas=0.3.30=hf2bb037_2
  - libopenjpeg=2.5.4=haa24f5a_1
  - libpng=1.6.50=h5c318fc_0
  - libprotobuf=5.29.3=h14f15fd_1
  - libre2-11=2024.07.02=h313beb8_0
  - libssh2=1.11.1=h3e2b118_0
  - libthrift=0.22.0=hbe873a3_0
  - libtiff=4.7.0=h91aec0a_0
  - libunistring=1.3=h1799b2a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h528a072_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.6=py313hca03da5_1
  - matplotlib-base=3.10.6=py313haa222d5_1
  - narwhals=2.7.0=py313hca03da5_0
  - ncurses=6.5=hee39554_0
  - numexpr=2.14.1=py313h5fbe615_0
  - numpy=2.3.4=py313h4bb6f22_1
  - numpy-base=2.3.4=py313h23175f9_1
  - openssl=3.0.18=h9b4081a_0
  - orc=2.2.0=hec253e6_0
  - packaging=25.0=py313hca03da5_1
  - pandas=2.3.3=py313h3f644e9_1
  - pcre2=10.46=h1dacb4a_0
  - pillow=12.0.0=py313he2d6fe4_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - protobuf=5.29.3=py313h514c7bf_0
  - pyarrow=21.0.0=py313h6316d20_0
  - pycparser=2.23=py313hca03da5_0
  - pyparsing=3.2.0=py313hca03da5_0
  - pysocks=1.7.1=py313hca03da5_1
  - python=3.13.9=hc7d8306_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313hca03da5_0
  - re2=2024.07.02=h48ca7d4_0
  - readline=8.3=h0b18652_0
  - referencing=0.37.0=py313hca03da5_0
  - requests=2.32.5=py313hca03da5_1
  - rpds-py=0.28.0=py313h931abed_0
  - scikit-learn=1.7.2=py313h6316d20_0
  - scipy=1.16.3=py313h08a1045_0
  - setuptools=80.9.0=py313hca03da5_0
  - six=1.17.0=py313hca03da5_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.2.1=h313beb8_0
  - sqlite=3.51.0=hab6afd1_0
  - streamlit=1.51.0=py313hca03da5_0
  - tenacity=9.1.2=py313hca03da5_0
  - threadpoolctl=3.5.0=py313h7eb115d_0
  - tk=8.6.15=hcd8a7d5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.5.1=py313h80987f9_0
  - typing-extensions=4.15.0=py313hca03da5_0
  - typing_extensions=4.15.0=py313hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313hca03da5_0
  - utf8proc=2.6.1=h80987f9_1
  - wheel=0.45.1=py313hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
